# Generated by Django 4.0.5 on 2022-06-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آگهی')),
                ('price', models.CharField(max_length=100, verbose_name='قیمت')),
                ('description', models.CharField(max_length=300, verbose_name='قیمت')),
                ('advertise_url', models.URLField(null=True, verbose_name='لینک')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی ها',
            },
        ),
    ]
